# Generated by Django 5.2.7 on 2025-11-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='user', max_length=128),
            preserve_default=False,
        ),
    ]
