# Generated by Django 5.2.7 on 2025-11-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='NUID',
            field=models.CharField(default='user', max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
