# Generated by Django 5.2.7 on 2025-11-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_user_nuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='NUID',
            new_name='nuid',
        ),
    ]
