# Generated by Django 5.2.7 on 2025-11-29 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_rename_nuid_user_nuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.DateTimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='scheduler.tutor')),
            ],
            options={
                'verbose_name_plural': 'Tutor Availability',
                'unique_together': {('tutor', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
