# Generated by Django 5.2.7 on 2025-11-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_tutoravailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoravailability',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
